
spring.datasource.url=jdbc:mysql://root:hUICPbWyDRokjPZDWjbCSVGcIuRQnaYi@junction.proxy.rlwy.net:21025/railway
spring.datasource.username=root
spring.datasource.password=hUlCPbWyDRokjPZDwjbcSVGclURQnaYi
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.application.name=Spring-Ai
spring.ai.google.genai.api-key=AIzaSyC7dJwApDCuRd6O-pflWWagEIOnXD9cT00
spring.ai.google.genai.project-id=gen-lang-client-0648093690